"""
This type stub file was generated by pyright.
"""

import logging
from collections.abc import Sequence
from typing import Any, Callable, Dict, List, Mapping, Optional, TypeVar
from opentelemetry.proto.common.v1.common_pb2 import AnyValue as PB2AnyValue, ArrayValue as PB2ArrayValue, InstrumentationScope as PB2InstrumentationScope, KeyValue as PB2KeyValue, KeyValueList as PB2KeyValueList
from opentelemetry.proto.resource.v1.resource_pb2 import Resource as PB2Resource
from opentelemetry.sdk.trace import Resource
from opentelemetry.sdk.util.instrumentation import InstrumentationScope
from opentelemetry.util.types import _ExtendedAttributes

_logger = ...
_TypingResourceT = TypeVar("_TypingResourceT")
_ResourceDataT = TypeVar("_ResourceDataT")
