"""
This type stub file was generated by pyright.
"""

from opentelemetry.sdk._logs._internal import LogData, LogDeprecatedInitWarning, LogDroppedAttributesWarning, LogLimits, LogRecord, LogRecordProcessor, Logger, LoggerProvider, LoggingHandler

__all__ = ["LogData", "Logger", "LoggerProvider", "LoggingHandler", "LogLimits", "LogRecord", "LogRecordProcessor", "LogDeprecatedInitWarning", "LogDroppedAttributesWarning"]
