"""
This type stub file was generated by pyright.
"""

import logging
import threading
from collections import OrderedDict
from collections.abc import MutableMapping
from typing import Mapping, Optional, Sequence, Tuple, Union
from opentelemetry.util import types

_VALID_ATTR_VALUE_TYPES = ...
_VALID_ANY_VALUE_TYPES = ...
_logger = ...
class BoundedAttributes(MutableMapping):
    """An ordered dict with a fixed max capacity.

    Oldest elements are dropped when the dict is full and a new element is
    added.
    """
    def __init__(self, maxlen: Optional[int] = ..., attributes: Optional[types._ExtendedAttributes] = ..., immutable: bool = ..., max_value_len: Optional[int] = ..., extended_attributes: bool = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __getitem__(self, key: str) -> types.AnyValue:
        ...
    
    def __setitem__(self, key: str, value: types.AnyValue) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __iter__(self): # -> Iterator[str]:
        ...
    
    def __len__(self) -> int:
        ...
    
    def copy(self): # -> OrderedDict[str, AnyValue]:
        ...
    


