"""
This type stub file was generated by pyright.
"""

"""Client and server classes corresponding to protobuf-defined services."""
GRPC_GENERATED_VERSION = ...
GRPC_VERSION = ...
EXPECTED_ERROR_RELEASE = ...
SCHEDULED_RELEASE_DATE = ...
_version_not_supported = ...
_version_not_supported = ...
if _version_not_supported:
    ...
class TraceServiceStub:
    """Service that can be used to push spans between one Application instrumented with
    OpenTelemetry and a collector, or between a collector and a central collector (in this
    case spans are sent/received to/from multiple Applications).
    """
    def __init__(self, channel) -> None:
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        ...
    


class TraceServiceServicer:
    """Service that can be used to push spans between one Application instrumented with
    OpenTelemetry and a collector, or between a collector and a central collector (in this
    case spans are sent/received to/from multiple Applications).
    """
    def Export(self, request, context):
        """Missing associated documentation comment in .proto file."""
        ...
    


def add_TraceServiceServicer_to_server(servicer, server): # -> None:
    ...

class TraceService:
    """Service that can be used to push spans between one Application instrumented with
    OpenTelemetry and a collector, or between a collector and a central collector (in this
    case spans are sent/received to/from multiple Applications).
    """
    @staticmethod
    def Export(request, target, options=..., channel_credentials=..., call_credentials=..., insecure=..., compression=..., wait_for_ready=..., timeout=..., metadata=...):
        ...
    


