# =============================================================================
# Application Infrastructure - dev Environment
# =============================================================================
# Generated by scripts/setup-terraform-lambda.sh
# Customize these values for your dev environment
# =============================================================================

project_name = "aws-ai"
environment  = "dev"
aws_region   = "us-east-1"
github_repo  = "gpazevedo/aws-ai"  # From bootstrap configuration

# ECR Repository (created by bootstrap)
ecr_repository_name = "aws-ai"  # Must match bootstrap configuration

# Lambda Configuration
lambda_memory_size  = 512
lambda_timeout      = 30
lambda_architecture = "arm64"  # or "x86_64"

# =============================================================================
# API Gateway Configuration (Standard Mode)
# =============================================================================
# API Gateway is the standard entry point for cloud deployments
# For local development, set enable_direct_access = true

enable_api_gateway_standard = true   # Enable API Gateway as standard entry point
enable_direct_access        = false  # Disable direct Lambda URLs (cloud deployment)

# Rate Limiting
api_throttle_burst_limit = 1000  # Lower limits for dev environment
api_throttle_rate_limit  = 500   # Requests per second

# Logging (verbose for dev)
api_log_retention_days = 7
api_logging_level      = "INFO"
enable_api_data_trace  = false  # Set to true for detailed request/response logging
enable_xray_tracing    = true   # Enable X-Ray for debugging

# Caching (disabled for dev)
enable_api_caching = false

# CORS (open for dev)
cors_allow_origins = ["*"]
cors_allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
cors_allow_headers = ["Content-Type", "Authorization", "X-Requested-With"]

# Additional tags
additional_tags = {
  CostCenter = "engineering"
  Team       = "platform"
}
