"""
This type stub file was generated by pyright.
"""

from typing import Collection
from packaging.requirements import Requirement
from opentelemetry.util._importlib_metadata import Distribution

logger = ...
class DependencyConflict:
    """Represents a dependency conflict in OpenTelemetry instrumentation.

    This class is used to track conflicts between required dependencies and the
    actual installed packages. It supports two scenarios:

    1. Standard conflicts where all dependencies are required
    2. Either/or conflicts where only one of a set of dependencies is required

    Attributes:
        required: The required dependency specification that conflicts with what's installed.
        found: The actual dependency that was found installed (if any).
        required_any: Collection of dependency specifications where any one would satisfy
            the requirement (for either/or scenarios).
        found_any: Collection of actual dependencies found for either/or scenarios.
    """
    required: str | None = ...
    found: str | None = ...
    required_any: Collection[str] = ...
    found_any: Collection[str] = ...
    def __init__(self, required: str | None = ..., found: str | None = ..., required_any: Collection[str] = ..., found_any: Collection[str] = ...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class DependencyConflictError(Exception):
    conflict: DependencyConflict
    def __init__(self, conflict: DependencyConflict) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def get_dist_dependency_conflicts(dist: Distribution) -> DependencyConflict | None:
    ...

def get_dependency_conflicts(deps: Collection[str | Requirement], deps_any: Collection[str | Requirement] | None = ...) -> DependencyConflict | None:
    ...

