"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager
from typing import Any, Dict, Generator, Sequence
from opentelemetry.trace import StatusCode

propagator = ...
_SUPPRESS_INSTRUMENTATION_KEY_PLAIN = ...
def extract_attributes_from_object(obj: Any, attributes: Sequence[str], existing: Dict[str, str] | None = ...) -> Dict[str, str]:
    ...

def http_status_to_status_code(status: int, allow_redirect: bool = ..., server_span: bool = ...) -> StatusCode:
    """Converts an HTTP status code to an OpenTelemetry canonical status code

    Args:
        status (int): HTTP status code
    """
    ...

def unwrap(obj: object, attr: str): # -> None:
    """Given a function that was wrapped by wrapt.wrap_function_wrapper, unwrap it

    The object containing the function to unwrap may be passed as dotted module path string.

    Args:
        obj: Object that holds a reference to the wrapped function or dotted import path as string
        attr (str): Name of the wrapped function
    """
    ...

def is_instrumentation_enabled() -> bool:
    ...

def is_http_instrumentation_enabled() -> bool:
    ...

@contextmanager
def suppress_instrumentation() -> Generator[None]:
    """Suppress instrumentation within the context."""
    ...

@contextmanager
def suppress_http_instrumentation() -> Generator[None]:
    """Suppress instrumentation within the context."""
    ...

