"""
This type stub file was generated by pyright.
"""

import logging
from collections import defaultdict
from typing import List, Optional, Sequence
from opentelemetry.exporter.otlp.proto.common._internal import _encode_attributes, _encode_instrumentation_scope, _encode_resource, _encode_span_id, _encode_trace_id
from opentelemetry.proto.collector.trace.v1.trace_service_pb2 import ExportTraceServiceRequest as PB2ExportTraceServiceRequest
from opentelemetry.proto.trace.v1.trace_pb2 import ResourceSpans as PB2ResourceSpans, ScopeSpans as PB2ScopeSpans, Span as PB2SPan, SpanFlags as PB2SpanFlags, Status as PB2Status
from opentelemetry.sdk.trace import Event, ReadableSpan
from opentelemetry.trace import Link, SpanKind
from opentelemetry.trace.span import SpanContext, Status, TraceState

_SPAN_KIND_MAP = ...
_logger = ...
def encode_spans(sdk_spans: Sequence[ReadableSpan]) -> PB2ExportTraceServiceRequest:
    ...

