"""
This type stub file was generated by pyright.
"""

import logging
from os import environ
from typing import Dict, Optional, Sequence, Tuple, Union
from grpc import ChannelCredentials, Compression
from opentelemetry.exporter.otlp.proto.common.trace_encoder import encode_spans
from opentelemetry.exporter.otlp.proto.grpc.exporter import OTLPExporterMixin, _get_credentials, environ_to_compression, get_resource_data
from opentelemetry.proto.collector.trace.v1.trace_service_pb2 import ExportTraceServiceRequest
from opentelemetry.proto.collector.trace.v1.trace_service_pb2_grpc import TraceServiceStub
from opentelemetry.proto.common.v1.common_pb2 import InstrumentationScope
from opentelemetry.proto.trace.v1.trace_pb2 import ResourceSpans, ScopeSpans, Span as CollectorSpan, Status
from opentelemetry.sdk.environment_variables import OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE, OTEL_EXPORTER_OTLP_TRACES_CLIENT_CERTIFICATE, OTEL_EXPORTER_OTLP_TRACES_CLIENT_KEY, OTEL_EXPORTER_OTLP_TRACES_COMPRESSION, OTEL_EXPORTER_OTLP_TRACES_ENDPOINT, OTEL_EXPORTER_OTLP_TRACES_HEADERS, OTEL_EXPORTER_OTLP_TRACES_INSECURE, OTEL_EXPORTER_OTLP_TRACES_TIMEOUT, _OTEL_PYTHON_EXPORTER_OTLP_GRPC_TRACES_CREDENTIAL_PROVIDER
from opentelemetry.sdk.trace import ReadableSpan
from opentelemetry.sdk.trace.export import SpanExportResult, SpanExporter

"""OTLP Span Exporter"""
logger = ...
class OTLPSpanExporter(SpanExporter, OTLPExporterMixin[Sequence[ReadableSpan], ExportTraceServiceRequest, SpanExportResult, TraceServiceStub,]):
    """OTLP span exporter

    Args:
        endpoint: OpenTelemetry Collector receiver endpoint
        insecure: Connection type
        credentials: Credentials object for server authentication
        headers: Headers to send when exporting
        timeout: Backend request timeout in seconds
        compression: gRPC compression method to use
    """
    def __init__(self, endpoint: Optional[str] = ..., insecure: Optional[bool] = ..., credentials: Optional[ChannelCredentials] = ..., headers: Optional[Union[TypingSequence[Tuple[str, str]], Dict[str, str], str]] = ..., timeout: Optional[float] = ..., compression: Optional[Compression] = ..., channel_options: Optional[Tuple[Tuple[str, str]]] = ...) -> None:
        ...
    
    def export(self, spans: Sequence[ReadableSpan]) -> SpanExportResult:
        ...
    
    def shutdown(self, timeout_millis: float = ..., **kwargs) -> None:
        ...
    
    def force_flush(self, timeout_millis: int = ...) -> bool:
        """Nothing is buffered in this exporter, so this method does nothing."""
        ...
    


