"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from logging import getLogger
from os import environ
from time import time_ns
from typing import Optional, cast, overload
from typing_extensions import deprecated
from opentelemetry._logs.severity import SeverityNumber
from opentelemetry.context import get_current
from opentelemetry.context.context import Context
from opentelemetry.environment_variables import _OTEL_PYTHON_LOGGER_PROVIDER
from opentelemetry.trace import get_current_span
from opentelemetry.trace.span import TraceFlags
from opentelemetry.util._once import Once
from opentelemetry.util._providers import _load_provider
from opentelemetry.util.types import AnyValue, _ExtendedAttributes

"""
The OpenTelemetry logging API describes the classes used to generate logs and events.

The :class:`.LoggerProvider` provides users access to the :class:`.Logger`.

This module provides abstract (i.e. unimplemented) classes required for
logging, and a concrete no-op implementation :class:`.NoOpLogger` that allows applications
to use the API package alone without a supporting implementation.

To get a logger, you need to provide the package name from which you are
calling the logging APIs to OpenTelemetry by calling `LoggerProvider.get_logger`
with the calling module name and the version of your package.

The following code shows how to obtain a logger using the global :class:`.LoggerProvider`::

    from opentelemetry._logs import get_logger

    logger = get_logger("example-logger")

.. versionadded:: 1.15.0
"""
_logger = ...
class LogRecord(ABC):
    """A LogRecord instance represents an event being logged.

    LogRecord instances are created and emitted via `Logger`
    every time something is logged. They contain all the information
    pertinent to the event being logged.
    """
    @overload
    def __init__(self, *, timestamp: Optional[int] = ..., observed_timestamp: Optional[int] = ..., context: Optional[Context] = ..., severity_text: Optional[str] = ..., severity_number: Optional[SeverityNumber] = ..., body: AnyValue = ..., attributes: Optional[_ExtendedAttributes] = ..., event_name: Optional[str] = ...) -> None:
        ...
    
    @overload
    @deprecated("LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.")
    def __init__(self, *, timestamp: Optional[int] = ..., observed_timestamp: Optional[int] = ..., trace_id: Optional[int] = ..., span_id: Optional[int] = ..., trace_flags: Optional[TraceFlags] = ..., severity_text: Optional[str] = ..., severity_number: Optional[SeverityNumber] = ..., body: AnyValue = ..., attributes: Optional[_ExtendedAttributes] = ...) -> None:
        ...
    
    def __init__(self, *, timestamp: Optional[int] = ..., observed_timestamp: Optional[int] = ..., context: Optional[Context] = ..., trace_id: Optional[int] = ..., span_id: Optional[int] = ..., trace_flags: Optional[TraceFlags] = ..., severity_text: Optional[str] = ..., severity_number: Optional[SeverityNumber] = ..., body: AnyValue = ..., attributes: Optional[_ExtendedAttributes] = ..., event_name: Optional[str] = ...) -> None:
        ...
    


class Logger(ABC):
    """Handles emitting events and logs via `LogRecord`."""
    def __init__(self, name: str, version: Optional[str] = ..., schema_url: Optional[str] = ..., attributes: Optional[_ExtendedAttributes] = ...) -> None:
        ...
    
    @overload
    def emit(self, *, timestamp: int | None = ..., observed_timestamp: int | None = ..., context: Context | None = ..., severity_number: SeverityNumber | None = ..., severity_text: str | None = ..., body: AnyValue | None = ..., attributes: _ExtendedAttributes | None = ..., event_name: str | None = ...) -> None:
        ...
    
    @overload
    def emit(self, record: LogRecord) -> None:
        ...
    
    @abstractmethod
    def emit(self, record: LogRecord | None = ..., *, timestamp: int | None = ..., observed_timestamp: int | None = ..., context: Context | None = ..., severity_number: SeverityNumber | None = ..., severity_text: str | None = ..., body: AnyValue | None = ..., attributes: _ExtendedAttributes | None = ..., event_name: str | None = ...) -> None:
        """Emits a :class:`LogRecord` representing a log to the processing pipeline."""
        ...
    


class NoOpLogger(Logger):
    """The default Logger used when no Logger implementation is available.

    All operations are no-op.
    """
    @overload
    def emit(self, *, timestamp: int | None = ..., observed_timestamp: int | None = ..., context: Context | None = ..., severity_number: SeverityNumber | None = ..., severity_text: str | None = ..., body: AnyValue | None = ..., attributes: _ExtendedAttributes | None = ..., event_name: str | None = ...) -> None:
        ...
    
    @overload
    def emit(self, record: LogRecord) -> None:
        ...
    
    def emit(self, record: LogRecord | None = ..., *, timestamp: int | None = ..., observed_timestamp: int | None = ..., context: Context | None = ..., severity_number: SeverityNumber | None = ..., severity_text: str | None = ..., body: AnyValue | None = ..., attributes: _ExtendedAttributes | None = ..., event_name: str | None = ...) -> None:
        ...
    


class ProxyLogger(Logger):
    def __init__(self, name: str, version: Optional[str] = ..., schema_url: Optional[str] = ..., attributes: Optional[_ExtendedAttributes] = ...) -> None:
        ...
    
    @overload
    def emit(self, *, timestamp: int | None = ..., observed_timestamp: int | None = ..., context: Context | None = ..., severity_number: SeverityNumber | None = ..., severity_text: str | None = ..., body: AnyValue | None = ..., attributes: _ExtendedAttributes | None = ..., event_name: str | None = ...) -> None:
        ...
    
    @overload
    def emit(self, record: LogRecord) -> None:
        ...
    
    def emit(self, record: LogRecord | None = ..., *, timestamp: int | None = ..., observed_timestamp: int | None = ..., context: Context | None = ..., severity_number: SeverityNumber | None = ..., severity_text: str | None = ..., body: AnyValue | None = ..., attributes: _ExtendedAttributes | None = ..., event_name: str | None = ...) -> None:
        ...
    


class LoggerProvider(ABC):
    """
    LoggerProvider is the entry point of the API. It provides access to Logger instances.
    """
    @abstractmethod
    def get_logger(self, name: str, version: Optional[str] = ..., schema_url: Optional[str] = ..., attributes: Optional[_ExtendedAttributes] = ...) -> Logger:
        """Returns a `Logger` for use by the given instrumentation library.

        For any two calls with identical parameters, it is undefined whether the same
        or different `Logger` instances are returned.

        This function may return different `Logger` types (e.g. a no-op logger
        vs. a functional logger).

        Args:
            name: The name of the instrumenting module, package or class.
                This should *not* be the name of the module, package or class that is
                instrumented but the name of the code doing the instrumentation.
                E.g., instead of ``"requests"``, use
                ``"opentelemetry.instrumentation.requests"``.

                For log sources which define a logger name (e.g. logging.Logger.name)
                the Logger Name should be recorded as the instrumentation scope name.

            version: Optional. The version string of the
                instrumenting library.  Usually this should be the same as
                ``importlib.metadata.version(instrumenting_library_name)``.

            schema_url: Optional. Specifies the Schema URL of the emitted telemetry.

            attributes: Optional. Specifies the instrumentation scope attributes to
                associate with emitted telemetry.
        """
        ...
    


class NoOpLoggerProvider(LoggerProvider):
    """The default LoggerProvider used when no LoggerProvider implementation is available."""
    def get_logger(self, name: str, version: Optional[str] = ..., schema_url: Optional[str] = ..., attributes: Optional[_ExtendedAttributes] = ...) -> Logger:
        """Returns a NoOpLogger."""
        ...
    


class ProxyLoggerProvider(LoggerProvider):
    def get_logger(self, name: str, version: Optional[str] = ..., schema_url: Optional[str] = ..., attributes: Optional[_ExtendedAttributes] = ...) -> Logger:
        ...
    


_LOGGER_PROVIDER_SET_ONCE = ...
_LOGGER_PROVIDER: Optional[LoggerProvider] = ...
_PROXY_LOGGER_PROVIDER = ...
def get_logger_provider() -> LoggerProvider:
    """Gets the current global :class:`~.LoggerProvider` object."""
    ...

def set_logger_provider(logger_provider: LoggerProvider) -> None:
    """Sets the current global :class:`~.LoggerProvider` object.

    This can only be done once, a warning will be logged if any further attempt
    is made.
    """
    ...

def get_logger(instrumenting_module_name: str, instrumenting_library_version: str = ..., logger_provider: Optional[LoggerProvider] = ..., schema_url: Optional[str] = ..., attributes: Optional[_ExtendedAttributes] = ...) -> Logger:
    """Returns a `Logger` for use within a python process.

    This function is a convenience wrapper for
    opentelemetry.sdk._logs.LoggerProvider.get_logger.

    If logger_provider param is omitted the current configured one is used.
    """
    ...

