"""
This type stub file was generated by pyright.
"""

import abc
import enum
import logging
import sys
from os import environ, linesep
from typing import Callable, IO, Optional, Sequence
from opentelemetry.context import _SUPPRESS_INSTRUMENTATION_KEY, attach, detach, set_value
from opentelemetry.sdk._logs import LogData, LogRecord, LogRecordProcessor
from opentelemetry.sdk._shared_internal import BatchProcessor, DuplicateFilter
from opentelemetry.sdk.environment_variables import OTEL_BLRP_EXPORT_TIMEOUT, OTEL_BLRP_MAX_EXPORT_BATCH_SIZE, OTEL_BLRP_MAX_QUEUE_SIZE, OTEL_BLRP_SCHEDULE_DELAY

_DEFAULT_SCHEDULE_DELAY_MILLIS = ...
_DEFAULT_MAX_EXPORT_BATCH_SIZE = ...
_DEFAULT_EXPORT_TIMEOUT_MILLIS = ...
_DEFAULT_MAX_QUEUE_SIZE = ...
_ENV_VAR_INT_VALUE_ERROR_MESSAGE = ...
_logger = ...
class LogExportResult(enum.Enum):
    SUCCESS = ...
    FAILURE = ...


class LogExporter(abc.ABC):
    """Interface for exporting logs.
    Interface to be implemented by services that want to export logs received
    in their own format.
    To export data this MUST be registered to the :class`opentelemetry.sdk._logs.Logger` using a
    log processor.
    """
    @abc.abstractmethod
    def export(self, batch: Sequence[LogData]): # -> None:
        """Exports a batch of logs.
        Args:
            batch: The list of `LogData` objects to be exported
        Returns:
            The result of the export
        """
        ...
    
    @abc.abstractmethod
    def shutdown(self): # -> None:
        """Shuts down the exporter.

        Called when the SDK is shut down.
        """
        ...
    


class ConsoleLogExporter(LogExporter):
    """Implementation of :class:`LogExporter` that prints log records to the
    console.

    This class can be used for diagnostic purposes. It prints the exported
    log records to the console STDOUT.
    """
    def __init__(self, out: IO = ..., formatter: Callable[[LogRecord], str] = ...) -> None:
        ...
    
    def export(self, batch: Sequence[LogData]): # -> Literal[LogExportResult.SUCCESS]:
        ...
    
    def shutdown(self): # -> None:
        ...
    


class SimpleLogRecordProcessor(LogRecordProcessor):
    """This is an implementation of LogRecordProcessor which passes
    received logs in the export-friendly LogData representation to the
    configured LogExporter, as soon as they are emitted.
    """
    def __init__(self, exporter: LogExporter) -> None:
        ...
    
    def on_emit(self, log_data: LogData): # -> None:
        ...
    
    def shutdown(self): # -> None:
        ...
    
    def force_flush(self, timeout_millis: int = ...) -> bool:
        ...
    


class BatchLogRecordProcessor(LogRecordProcessor):
    """This is an implementation of LogRecordProcessor which creates batches of
    received logs in the export-friendly LogData representation and
    send to the configured LogExporter, as soon as they are emitted.

    `BatchLogRecordProcessor` is configurable with the following environment
    variables which correspond to constructor parameters:

    - :envvar:`OTEL_BLRP_SCHEDULE_DELAY`
    - :envvar:`OTEL_BLRP_MAX_QUEUE_SIZE`
    - :envvar:`OTEL_BLRP_MAX_EXPORT_BATCH_SIZE`
    - :envvar:`OTEL_BLRP_EXPORT_TIMEOUT`

    All the logic for emitting logs, shutting down etc. resides in the BatchProcessor class.
    """
    def __init__(self, exporter: LogExporter, schedule_delay_millis: float | None = ..., max_export_batch_size: int | None = ..., export_timeout_millis: float | None = ..., max_queue_size: int | None = ...) -> None:
        ...
    
    def on_emit(self, log_data: LogData) -> None:
        ...
    
    def shutdown(self): # -> None:
        ...
    
    def force_flush(self, timeout_millis: Optional[int] = ...) -> bool:
        ...
    


