"""
This type stub file was generated by pyright.
"""

import typing
from opentelemetry.sdk._logs import LogData
from opentelemetry.sdk._logs.export import LogExportResult, LogExporter

class InMemoryLogExporter(LogExporter):
    """Implementation of :class:`.LogExporter` that stores logs in memory.

    This class can be used for testing purposes. It stores the exported logs
    in a list in memory that can be retrieved using the
    :func:`.get_finished_logs` method.
    """
    def __init__(self) -> None:
        ...
    
    def clear(self) -> None:
        ...
    
    def get_finished_logs(self) -> typing.Tuple[LogData, ...]:
        ...
    
    def export(self, batch: typing.Sequence[LogData]) -> LogExportResult:
        ...
    
    def shutdown(self) -> None:
        ...
    


