"""
This type stub file was generated by pyright.
"""

class Buckets:
    def __init__(self) -> None:
        ...
    
    @property
    def index_start(self) -> int:
        ...
    
    @index_start.setter
    def index_start(self, value: int) -> None:
        ...
    
    @property
    def index_end(self) -> int:
        ...
    
    @index_end.setter
    def index_end(self, value: int) -> None:
        ...
    
    @property
    def index_base(self) -> int:
        ...
    
    @index_base.setter
    def index_base(self, value: int) -> None:
        ...
    
    @property
    def counts(self): # -> list[int] | Any:
        ...
    
    def get_offset_counts(self): # -> list[int] | Any:
        ...
    
    def grow(self, needed: int, max_size: int) -> None:
        ...
    
    @property
    def offset(self) -> int:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __getitem__(self, key: int) -> int:
        ...
    
    def downscale(self, amount: int) -> None:
        """
        Rotates, then collapses 2 ** amount to 1 buckets.
        """
        ...
    
    def increment_bucket(self, bucket_index: int, increment: int = ...) -> None:
        ...
    
    def copy_empty(self) -> Buckets:
        ...
    


