"""
This type stub file was generated by pyright.
"""

def entry_points(**params): # -> EntryPoints:
    """Replacement for importlib_metadata.entry_points that caches getting all the entry points.

    That part can be very slow, and OTel uses this function many times."""
    ...

__all__ = ["entry_points", "version", "EntryPoint", "EntryPoints", "requires", "Distribution", "distributions", "PackageNotFoundError"]
