"""
This type stub file was generated by pyright.
"""

from abc import ABC
from typing import Callable, Dict, Generic, List, Optional, Sequence as TypingSequence, Tuple, TypeVar, Union
from typing_extensions import deprecated
from grpc import ChannelCredentials, Compression
from opentelemetry.proto.collector.logs.v1.logs_service_pb2 import ExportLogsServiceRequest
from opentelemetry.proto.collector.logs.v1.logs_service_pb2_grpc import LogsServiceStub
from opentelemetry.proto.collector.metrics.v1.metrics_service_pb2 import ExportMetricsServiceRequest
from opentelemetry.proto.collector.metrics.v1.metrics_service_pb2_grpc import MetricsServiceStub
from opentelemetry.proto.collector.trace.v1.trace_service_pb2 import ExportTraceServiceRequest
from opentelemetry.proto.collector.trace.v1.trace_service_pb2_grpc import TraceServiceStub
from opentelemetry.sdk._logs import LogData
from opentelemetry.sdk._logs.export import LogExportResult
from opentelemetry.sdk.metrics.export import MetricExportResult, MetricsData
from opentelemetry.sdk.resources import Resource as SDKResource
from opentelemetry.sdk.trace import ReadableSpan
from opentelemetry.sdk.trace.export import SpanExportResult

"""OTLP Exporter"""
_RETRYABLE_ERROR_CODES = ...
_MAX_RETRYS = ...
logger = ...
SDKDataT = TypeVar("SDKDataT", TypingSequence[LogData], MetricsData, TypingSequence[ReadableSpan])
ResourceDataT = TypeVar("ResourceDataT")
TypingResourceT = TypeVar("TypingResourceT")
ExportServiceRequestT = TypeVar("ExportServiceRequestT", ExportTraceServiceRequest, ExportMetricsServiceRequest, ExportLogsServiceRequest)
ExportResultT = TypeVar("ExportResultT", LogExportResult, MetricExportResult, SpanExportResult)
ExportStubT = TypeVar("ExportStubT", TraceServiceStub, MetricsServiceStub, LogsServiceStub)
_ENVIRON_TO_COMPRESSION = ...
class InvalidCompressionValueException(Exception):
    def __init__(self, environ_key: str, environ_value: str) -> None:
        ...
    


def environ_to_compression(environ_key: str) -> Optional[Compression]:
    ...

@deprecated("Use one of the encoders from opentelemetry-exporter-otlp-proto-common instead. Deprecated since version 1.18.0.")
def get_resource_data(sdk_resource_scope_data: Dict[SDKResource, ResourceDataT], resource_class: Callable[..., TypingResourceT], name: str) -> List[TypingResourceT]:
    ...

class OTLPExporterMixin(ABC, Generic[SDKDataT, ExportServiceRequestT, ExportResultT, ExportStubT]):
    """OTLP span exporter

    Args:
        endpoint: OpenTelemetry Collector receiver endpoint
        insecure: Connection type
        credentials: ChannelCredentials object for server authentication
        headers: Headers to send when exporting
        timeout: Backend request timeout in seconds
        compression: gRPC compression method to use
        channel_options: gRPC channel options
    """
    def __init__(self, stub: ExportStubT, result: ExportResultT, endpoint: Optional[str] = ..., insecure: Optional[bool] = ..., credentials: Optional[ChannelCredentials] = ..., headers: Optional[Union[TypingSequence[Tuple[str, str]], Dict[str, str], str]] = ..., timeout: Optional[float] = ..., compression: Optional[Compression] = ..., channel_options: Optional[Tuple[Tuple[str, str]]] = ...) -> None:
        ...
    
    def shutdown(self, timeout_millis: float = ..., **kwargs) -> None:
        ...
    


