"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod

class Mapping(ABC):
    """
    Parent class for `LogarithmMapping` and `ExponentialMapping`.
    """
    def __new__(cls, scale: int):
        ...
    
    @abstractmethod
    def map_to_index(self, value: float) -> int:
        """
        Maps positive floating point values to indexes corresponding to
        `Mapping.scale`. Implementations are not expected to handle zeros,
        +inf, NaN, or negative values.
        """
        ...
    
    @abstractmethod
    def get_lower_boundary(self, index: int) -> float:
        """
        Returns the lower boundary of a given bucket index. The index is
        expected to map onto a range that is at least partially inside the
        range of normal floating point values.  If the corresponding
        bucket's upper boundary is less than or equal to 2 ** -1022,
        :class:`~opentelemetry.sdk.metrics.MappingUnderflowError`
        will be raised. If the corresponding bucket's lower boundary is greater
        than ``sys.float_info.max``,
        :class:`~opentelemetry.sdk.metrics.MappingOverflowError`
        will be raised.
        """
        ...
    
    @property
    def scale(self) -> int:
        """
        Returns the parameter that controls the resolution of this mapping.
        See: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#exponential-scale
        """
        ...
    


