"""
This type stub file was generated by pyright.
"""

import math
import os
import weakref
import opentelemetry.sdk.metrics._internal
from abc import ABC, abstractmethod
from enum import Enum
from logging import getLogger
from os import environ, linesep
from sys import stdout
from threading import Event, Lock, RLock, Thread
from time import time_ns
from typing import Callable, IO, Iterable, Optional
from typing_extensions import final
from opentelemetry.context import _SUPPRESS_INSTRUMENTATION_KEY, attach, detach, set_value
from opentelemetry.sdk.environment_variables import OTEL_METRIC_EXPORT_INTERVAL, OTEL_METRIC_EXPORT_TIMEOUT
from opentelemetry.sdk.metrics._internal.aggregation import AggregationTemporality, DefaultAggregation
from opentelemetry.sdk.metrics._internal.exceptions import MetricsTimeoutError
from opentelemetry.sdk.metrics._internal.instrument import Counter, Gauge, Histogram, ObservableCounter, ObservableGauge, ObservableUpDownCounter, UpDownCounter, _Counter, _Gauge, _Histogram, _ObservableCounter, _ObservableGauge, _ObservableUpDownCounter, _UpDownCounter
from opentelemetry.sdk.metrics._internal.point import MetricsData
from opentelemetry.util._once import Once

_logger = ...
class MetricExportResult(Enum):
    """Result of exporting a metric

    Can be any of the following values:"""
    SUCCESS = ...
    FAILURE = ...


class MetricExporter(ABC):
    """Interface for exporting metrics.

    Interface to be implemented by services that want to export metrics received
    in their own format.

    Args:
        preferred_temporality: Used by `opentelemetry.sdk.metrics.export.PeriodicExportingMetricReader` to
            configure exporter level preferred temporality. See `opentelemetry.sdk.metrics.export.MetricReader` for
            more details on what preferred temporality is.
        preferred_aggregation: Used by `opentelemetry.sdk.metrics.export.PeriodicExportingMetricReader` to
            configure exporter level preferred aggregation. See `opentelemetry.sdk.metrics.export.MetricReader` for
            more details on what preferred aggregation is.
    """
    def __init__(self, preferred_temporality: dict[type, AggregationTemporality] | None = ..., preferred_aggregation: dict[type, opentelemetry.sdk.metrics.view.Aggregation] | None = ...) -> None:
        ...
    
    @abstractmethod
    def export(self, metrics_data: MetricsData, timeout_millis: float = ..., **kwargs) -> MetricExportResult:
        """Exports a batch of telemetry data.

        Args:
            metrics: The list of `opentelemetry.sdk.metrics.export.Metric` objects to be exported

        Returns:
            The result of the export
        """
        ...
    
    @abstractmethod
    def force_flush(self, timeout_millis: float = ...) -> bool:
        """
        Ensure that export of any metrics currently received by the exporter
        are completed as soon as possible.
        """
        ...
    
    @abstractmethod
    def shutdown(self, timeout_millis: float = ..., **kwargs) -> None:
        """Shuts down the exporter.

        Called when the SDK is shut down.
        """
        ...
    


class ConsoleMetricExporter(MetricExporter):
    """Implementation of :class:`MetricExporter` that prints metrics to the
    console.

    This class can be used for diagnostic purposes. It prints the exported
    metrics to the console STDOUT.
    """
    def __init__(self, out: IO = ..., formatter: Callable[[opentelemetry.sdk.metrics.export.MetricsData], str] = ..., preferred_temporality: dict[type, AggregationTemporality] | None = ..., preferred_aggregation: dict[type, opentelemetry.sdk.metrics.view.Aggregation] | None = ...) -> None:
        ...
    
    def export(self, metrics_data: MetricsData, timeout_millis: float = ..., **kwargs) -> MetricExportResult:
        ...
    
    def shutdown(self, timeout_millis: float = ..., **kwargs) -> None:
        ...
    
    def force_flush(self, timeout_millis: float = ...) -> bool:
        ...
    


class MetricReader(ABC):
    """
    Base class for all metric readers

    Args:
        preferred_temporality: A mapping between instrument classes and
            aggregation temporality. By default uses CUMULATIVE for all instrument
            classes. This mapping will be used to define the default aggregation
            temporality of every instrument class. If the user wants to make a
            change in the default aggregation temporality of an instrument class,
            it is enough to pass here a dictionary whose keys are the instrument
            classes and the values are the corresponding desired aggregation
            temporalities of the classes that the user wants to change, not all of
            them. The classes not included in the passed dictionary will retain
            their association to their default aggregation temporalities.
        preferred_aggregation: A mapping between instrument classes and
            aggregation instances. By default maps all instrument classes to an
            instance of `DefaultAggregation`. This mapping will be used to
            define the default aggregation of every instrument class. If the
            user wants to make a change in the default aggregation of an
            instrument class, it is enough to pass here a dictionary whose keys
            are the instrument classes and the values are the corresponding
            desired aggregation for the instrument classes that the user wants
            to change, not necessarily all of them. The classes not included in
            the passed dictionary will retain their association to their
            default aggregations. The aggregation defined here will be
            overridden by an aggregation defined by a view that is not
            `DefaultAggregation`.

    .. document protected _receive_metrics which is a intended to be overridden by subclass
    .. automethod:: _receive_metrics
    """
    def __init__(self, preferred_temporality: dict[type, AggregationTemporality] | None = ..., preferred_aggregation: dict[type, opentelemetry.sdk.metrics.view.Aggregation] | None = ...) -> None:
        ...
    
    @final
    def collect(self, timeout_millis: float = ...) -> None:
        """Collects the metrics from the internal SDK state and
        invokes the `_receive_metrics` with the collection.

        Args:
            timeout_millis: Amount of time in milliseconds before this function
              raises a timeout error.

        If any of the underlying ``collect`` methods called by this method
        fails by any reason (including timeout) an exception will be raised
        detailing the individual errors that caused this function to fail.
        """
        ...
    
    def force_flush(self, timeout_millis: float = ...) -> bool:
        ...
    
    @abstractmethod
    def shutdown(self, timeout_millis: float = ..., **kwargs) -> None:
        """Shuts down the MetricReader. This method provides a way
        for the MetricReader to do any cleanup required. A metric reader can
        only be shutdown once, any subsequent calls are ignored and return
        failure status.

        When a `MetricReader` is registered on a
        :class:`~opentelemetry.sdk.metrics.MeterProvider`,
        :meth:`~opentelemetry.sdk.metrics.MeterProvider.shutdown` will invoke this
        automatically.
        """
        ...
    


class InMemoryMetricReader(MetricReader):
    """Implementation of `MetricReader` that returns its metrics from :func:`get_metrics_data`.

    This is useful for e.g. unit tests.
    """
    def __init__(self, preferred_temporality: dict[type, AggregationTemporality] | None = ..., preferred_aggregation: dict[type, opentelemetry.sdk.metrics.view.Aggregation] | None = ...) -> None:
        ...
    
    def get_metrics_data(self) -> Optional[opentelemetry.sdk.metrics.export.MetricsData]:
        """Reads and returns current metrics from the SDK"""
        ...
    
    def shutdown(self, timeout_millis: float = ..., **kwargs) -> None:
        ...
    


class PeriodicExportingMetricReader(MetricReader):
    """`PeriodicExportingMetricReader` is an implementation of `MetricReader`
    that collects metrics based on a user-configurable time interval, and passes the
    metrics to the configured exporter. If the time interval is set to `math.inf`, the
    reader will not invoke periodic collection.

    The configured exporter's :py:meth:`~MetricExporter.export` method will not be called
    concurrently.
    """
    def __init__(self, exporter: MetricExporter, export_interval_millis: Optional[float] = ..., export_timeout_millis: Optional[float] = ...) -> None:
        ...
    
    def shutdown(self, timeout_millis: float = ..., **kwargs) -> None:
        ...
    
    def force_flush(self, timeout_millis: float = ...) -> bool:
        ...
    


