#!/bin/bash
# =============================================================================
# Setup Base Terraform Configuration
# =============================================================================
# This script creates the foundational Terraform files that are shared across
# all services (Lambda and AppRunner). Run this once before adding services.
#
# Usage: ./scripts/setup-terraform-base.sh
# =============================================================================

set -e

TERRAFORM_DIR="terraform"
BOOTSTRAP_DIR="bootstrap"
ENVIRONMENTS=("dev" "test" "prod")

echo "🚀 Setting up base Terraform configuration..."
echo ""

# =============================================================================
# Read Bootstrap Configuration
# =============================================================================

if [ ! -f "$BOOTSTRAP_DIR/terraform.tfvars" ]; then
  echo "⚠️  Warning: Bootstrap terraform.tfvars not found"
  echo "   Using default values for examples"
  echo "   You should run bootstrap first: cp bootstrap/terraform.tfvars.example bootstrap/terraform.tfvars"
  echo ""
  PROJECT_NAME="<YOUR-PROJECT>"
  AWS_REGION="us-east-1"
  GITHUB_ORG="<YOUR-ORG>"
  GITHUB_REPO="<YOUR-REPO>"
else
  # Read configuration from bootstrap
  PROJECT_NAME=$(grep '^project_name' "$BOOTSTRAP_DIR/terraform.tfvars" | cut -d'=' -f2 | cut -d'#' -f1 | tr -d ' "')
  AWS_REGION=$(grep '^aws_region' "$BOOTSTRAP_DIR/terraform.tfvars" | cut -d'=' -f2 | cut -d'#' -f1 | tr -d ' "')
  GITHUB_ORG=$(grep '^github_org' "$BOOTSTRAP_DIR/terraform.tfvars" | cut -d'=' -f2 | cut -d'#' -f1 | tr -d ' "')
  GITHUB_REPO=$(grep '^github_repo' "$BOOTSTRAP_DIR/terraform.tfvars" | cut -d'=' -f2 | cut -d'#' -f1 | tr -d ' "')
fi

# Set defaults if not found
: ${GITHUB_ORG:="<YOUR-ORG>"}
: ${GITHUB_REPO:="<YOUR-REPO>"}

echo "📋 Configuration:"
echo "   Project: $PROJECT_NAME"
echo "   Region: $AWS_REGION"
echo "   GitHub: $GITHUB_ORG/$GITHUB_REPO"
echo ""

# Create terraform directory if it doesn't exist
mkdir -p "$TERRAFORM_DIR/environments"

# =============================================================================
# Create main.tf
# =============================================================================
if [ ! -f "$TERRAFORM_DIR/main.tf" ]; then
  echo "📝 Creating terraform/main.tf..."
  cat > "$TERRAFORM_DIR/main.tf" <<'EOF'
# =============================================================================
# Application Infrastructure - Main Configuration
# =============================================================================
# This file defines the core infrastructure for your application
# Generated by scripts/setup-terraform-base.sh
# =============================================================================

terraform {
  required_version = ">= 1.13"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Backend configuration is loaded from environments/*.hcl files
  # Initialize with: terraform init -backend-config=environments/dev-backend.hcl
  backend "s3" {
    # Backend config provided via -backend-config flag
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = var.project_name
      CostCenter    = var.cost_center
      Team          = var.team
      Environment = var.environment
      ManagedBy   = "Terraform"
      Repository  = var.github_repo
    }
  }
}

# Get current AWS account ID
data "aws_caller_identity" "current" {}

# Get ECR repository (created by bootstrap)
data "aws_ecr_repository" "app" {
  name = var.ecr_repository_name
}
EOF
  echo "✅ Created terraform/main.tf"
else
  echo "ℹ️  Skipping main.tf (already exists)"
fi

# =============================================================================
# Create variables.tf (Common Variables Only)
# =============================================================================
if [ ! -f "$TERRAFORM_DIR/variables.tf" ]; then
  echo "📝 Creating terraform/variables.tf..."
  cat > "$TERRAFORM_DIR/variables.tf" <<'EOF'
# =============================================================================
# Application Infrastructure - Common Variables
# =============================================================================
# Generated by scripts/setup-terraform-base.sh
# Service-specific variables are in lambda-variables.tf and apprunner-variables.tf
# =============================================================================

variable "project_name" {
  description = "Project name (must match bootstrap configuration)"
  type        = string
}

variable "environment" {
  description = "Environment name (dev, test, prod)"
  type        = string
}

variable "aws_region" {
  description = "AWS region"
  type        = string
}

variable "github_repo" {
  description = "GitHub repository name (org/repo)"
  type        = string
}

variable "ecr_repository_name" {
  description = "ECR repository name for container images"
  type        = string
}

# =============================================================================
# API Gateway Configuration (Standard Mode)
# =============================================================================

variable "enable_api_gateway_standard" {
  description = "Enable API Gateway as standard entry point (recommended for cloud deployments)"
  type        = bool
  default     = true
}

variable "enable_direct_access" {
  description = "Enable direct access URLs (Lambda Function URLs, App Runner direct). Set to true for local development."
  type        = bool
  default     = false
}

# Legacy variable for backward compatibility
variable "enable_api_gateway" {
  description = "DEPRECATED: Use enable_api_gateway_standard instead. Enable API Gateway for Lambda functions"
  type        = bool
  default     = true
}

# Rate Limiting / Throttling
variable "api_throttle_burst_limit" {
  description = "API Gateway throttle burst limit (requests)"
  type        = number
  default     = 5000
}

variable "api_throttle_rate_limit" {
  description = "API Gateway throttle rate limit (requests per second)"
  type        = number
  default     = 10000
}

# Logging and Monitoring
variable "api_log_retention_days" {
  description = "CloudWatch log retention for API Gateway logs (days)"
  type        = number
  default     = 7
}

variable "api_logging_level" {
  description = "API Gateway logging level (OFF, ERROR, INFO)"
  type        = string
  default     = "INFO"

  validation {
    condition     = contains(["OFF", "ERROR", "INFO"], var.api_logging_level)
    error_message = "Logging level must be OFF, ERROR, or INFO"
  }
}

variable "enable_api_data_trace" {
  description = "Enable full request/response data logging (verbose, use with caution)"
  type        = bool
  default     = false
}

variable "enable_xray_tracing" {
  description = "Enable AWS X-Ray tracing for API Gateway"
  type        = bool
  default     = false
}

# Caching
variable "enable_api_caching" {
  description = "Enable API Gateway caching"
  type        = bool
  default     = false
}

# CORS Configuration
variable "cors_allow_origins" {
  description = "CORS allowed origins"
  type        = list(string)
  default     = ["*"]
}

variable "cors_allow_methods" {
  description = "CORS allowed HTTP methods"
  type        = list(string)
  default     = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
}

variable "cors_allow_headers" {
  description = "CORS allowed headers"
  type        = list(string)
  default     = ["Content-Type", "Authorization", "X-Requested-With"]
}

# =============================================================================
# API Key Authentication
# =============================================================================

variable "enable_api_key" {
  description = "Enable API Key authentication for API Gateway"
  type        = bool
  default     = true
}

variable "api_key_name" {
  description = "Name for the API Key (if enabled)"
  type        = string
  default     = ""
}

variable "api_usage_plan_quota_limit" {
  description = "Maximum number of requests per period (0 = unlimited)"
  type        = number
  default     = 0
}

variable "api_usage_plan_quota_period" {
  description = "Time period for quota (DAY, WEEK, MONTH)"
  type        = string
  default     = "MONTH"

  validation {
    condition     = contains(["DAY", "WEEK", "MONTH"], var.api_usage_plan_quota_period)
    error_message = "Quota period must be DAY, WEEK, or MONTH"
  }
}

# =============================================================================
# Tags
# =============================================================================

variable "cost_center" {
  description = "Cost center for resource tagging and cost allocation"
  type        = string
  default     = "engineering"
}

variable "team" {
  description = "Team responsible for the resources"
  type        = string
  default     = "platform"
}

variable "additional_tags" {
  description = "Additional tags to apply to all resources"
  type        = map(string)
  default     = {}
}
EOF
  echo "✅ Created terraform/variables.tf"
else
  echo "ℹ️  Skipping variables.tf (already exists)"
fi

# =============================================================================
# Create outputs.tf
# =============================================================================
if [ ! -f "$TERRAFORM_DIR/outputs.tf" ]; then
  echo "📝 Creating terraform/outputs.tf..."
  cat > "$TERRAFORM_DIR/outputs.tf" <<'EOF'
# =============================================================================
# Application Infrastructure - Outputs
# =============================================================================
# NOTE: Service-specific outputs (Lambda functions, URLs, etc.) are defined
# in each lambda-{service}.tf and apprunner-{service}.tf file.
# This file contains only shared outputs.
# =============================================================================

# =============================================================================
# API Gateway Outputs (Simplified)
# =============================================================================

output "api_gateway_url" {
  description = "API Gateway endpoint URL (standard entry point)"
  value       = try(module.api_gateway_shared[0].invoke_url, "Not enabled")
}

output "api_gateway_id" {
  description = "API Gateway REST API ID"
  value       = try(module.api_gateway_shared[0].api_id, "Not enabled")
}

output "api_gateway_stage" {
  description = "API Gateway stage name"
  value       = try(module.api_gateway_shared[0].stage_name, "Not enabled")
}

output "api_key_id" {
  description = "API Key ID (if enabled)"
  value       = try(module.api_gateway_shared[0].api_key_id, "Not enabled")
}

output "api_key_value" {
  description = "API Key value (sensitive, if enabled)"
  value       = try(module.api_gateway_shared[0].api_key_value, null)
  sensitive   = true
}

# =============================================================================
# Common Outputs
# =============================================================================

output "ecr_repository_url" {
  description = "ECR repository URL for container images"
  value       = data.aws_ecr_repository.app.repository_url
}

output "environment" {
  description = "Current environment"
  value       = var.environment
}

output "deployment_mode" {
  description = "Current deployment mode (api-gateway-standard or direct-access)"
  value       = var.enable_api_gateway_standard ? "api-gateway-standard" : (var.enable_direct_access ? "direct-access" : "legacy-api-gateway")
}

output "primary_endpoint" {
  description = "Primary application endpoint (API Gateway, if enabled)"
  value       = try(module.api_gateway_shared[0].invoke_url, "Not enabled - use service-specific Function URLs")
}

# =============================================================================
# Service-Specific Outputs
# =============================================================================
# Individual service outputs are defined in their respective files:
# - lambda-{service}.tf: lambda_{service}_function_name, lambda_{service}_url, etc.
# - apprunner-{service}.tf: apprunner_{service}_url, apprunner_{service}_arn, etc.
# =============================================================================
EOF
  echo "✅ Created terraform/outputs.tf"
else
  echo "ℹ️  Skipping outputs.tf (already exists)"
fi

# =============================================================================
# Create environment-specific tfvars files
# =============================================================================
for ENV in "${ENVIRONMENTS[@]}"; do
  TFVARS_FILE="$TERRAFORM_DIR/environments/${ENV}.tfvars"

  if [ ! -f "$TFVARS_FILE" ]; then
    echo "📝 Creating terraform/environments/${ENV}.tfvars..."

    cat > "$TFVARS_FILE" <<EOF
# =============================================================================
# Application Infrastructure - ${ENV} Environment
# =============================================================================
# Generated by scripts/setup-terraform-base.sh
# Customize these values for your ${ENV} environment
# =============================================================================

project_name = "${PROJECT_NAME}"
environment  = "${ENV}"
aws_region   = "${AWS_REGION}"
github_repo  = "${GITHUB_ORG}/${GITHUB_REPO}"

# ECR Repository (created by bootstrap)
ecr_repository_name = "${PROJECT_NAME}"  # Must match bootstrap configuration

# =============================================================================
# API Gateway Configuration (Standard Mode)
# =============================================================================

enable_api_gateway_standard = true   # Enable API Gateway as standard entry point
enable_direct_access        = false  # Disable direct Lambda URLs (cloud deployment)

# Rate Limiting
api_throttle_burst_limit = $([ "$ENV" = "prod" ] && echo "5000" || echo "1000")
api_throttle_rate_limit  = $([ "$ENV" = "prod" ] && echo "10000" || echo "500")

# Logging
api_log_retention_days = $([ "$ENV" = "prod" ] && echo "30" || echo "7")
api_logging_level      = "INFO"
enable_api_data_trace  = false
enable_xray_tracing    = $([ "$ENV" = "prod" ] && echo "false" || echo "true")

# Caching
enable_api_caching = false

# CORS
cors_allow_origins = $([ "$ENV" = "prod" ] && echo '["https://yourdomain.com"]' || echo '["*"]')
cors_allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
cors_allow_headers = ["Content-Type", "Authorization", "X-Requested-With"]

# API Key Authentication
enable_api_key              = false  # Set to true to enable API Key authentication
api_key_name                = ""     # Auto-generated if not specified
api_usage_plan_quota_limit  = 0      # Max requests per period (0 = unlimited)
api_usage_plan_quota_period = "MONTH"

# =============================================================================
# Resource Tagging
# =============================================================================

cost_center = "engineering"
team        = "platform"

# Additional tags (optional)
additional_tags = {}
EOF
  else
    echo "ℹ️  Skipping ${ENV}.tfvars (already exists)"
  fi
done

if [ ! -f "terraform/api-gateway.tf" ]; then
  echo "📝 Creating terraform/api-gateway.tf (modular structure)..."

  cat > "terraform/api-gateway.tf" <<'EOF'
# =============================================================================
# API Gateway Configuration (Standard Mode)
# =============================================================================
# This file configures API Gateway as the standard entry point for services
# Uses modular architecture for shared configuration and service-specific integrations
# Generated by scripts/setup-terraform-base.sh
# =============================================================================

locals {
  # Determine if API Gateway should be enabled
  api_gateway_enabled = var.enable_api_gateway_standard || var.enable_api_gateway
}

# =============================================================================
# Shared API Gateway Module
# =============================================================================

module "api_gateway_shared" {
  source = "./modules/api-gateway-shared"
  count  = local.api_gateway_enabled ? 1 : 0

  project_name = var.project_name
  environment  = var.environment
  api_name     = "${var.project_name}-${var.environment}-api"

  # NOTE: integration_ids will be automatically added by setup-terraform-lambda.sh
  # and setup-terraform-apprunner.sh when you add services. This ensures the
  # API Gateway deployment waits for all integrations to be created first.

  # Rate Limiting
  throttle_burst_limit = var.api_throttle_burst_limit
  throttle_rate_limit  = var.api_throttle_rate_limit

  # Logging and Monitoring
  log_retention_days   = var.api_log_retention_days
  api_logging_level    = var.api_logging_level
  enable_data_trace    = var.enable_api_data_trace
  enable_xray_tracing  = var.enable_xray_tracing

  # Caching
  enable_caching = var.enable_api_caching

  # API Key Authentication
  enable_api_key          = var.enable_api_key
  api_key_name            = var.api_key_name
  usage_plan_quota_limit  = var.api_usage_plan_quota_limit
  usage_plan_quota_period = var.api_usage_plan_quota_period

  tags = var.additional_tags
}

EOF

# =============================================================================

echo ""
echo "✅ Base Terraform configuration created successfully!"
echo ""
echo "📂 Created files:"
echo "   terraform/main.tf"
echo "   terraform/variables.tf"
echo "   terraform/outputs.tf"
echo "   terraform/README.md"
for ENV in "${ENVIRONMENTS[@]}"; do
  echo "   terraform/environments/${ENV}.tfvars"
done
echo ""
echo "🎯 Next Steps:"
echo ""
echo "1. Add Lambda services:"
echo "   ./scripts/setup-terraform-lambda.sh api false"
echo ""
echo "2. Add AppRunner services:"
echo "   ./scripts/setup-terraform-apprunner.sh web"
echo ""
echo "3. Setup backend configuration:"
echo "   make setup-terraform-backend"
echo ""
echo "4. Initialize and deploy:"
echo "   make app-init-dev app-apply-dev"
echo ""
fi
