"""
This type stub file was generated by pyright.
"""

import weakref
import opentelemetry.sdk.metrics
from atexit import register, unregister
from logging import getLogger
from os import environ
from threading import Lock
from time import time_ns
from typing import Optional, Sequence
from opentelemetry.metrics import Counter as APICounter, Histogram as APIHistogram, Meter as APIMeter, MeterProvider as APIMeterProvider, NoOpMeter, ObservableCounter as APIObservableCounter, ObservableGauge as APIObservableGauge, ObservableUpDownCounter as APIObservableUpDownCounter, UpDownCounter as APIUpDownCounter, _Gauge as APIGauge
from opentelemetry.sdk.environment_variables import OTEL_METRICS_EXEMPLAR_FILTER, OTEL_SDK_DISABLED
from opentelemetry.sdk.metrics._internal.exceptions import MetricsTimeoutError
from opentelemetry.sdk.metrics._internal.exemplar import AlwaysOffExemplarFilter, AlwaysOnExemplarFilter, ExemplarFilter, TraceBasedExemplarFilter
from opentelemetry.sdk.metrics._internal.instrument import _Counter, _Gauge, _Histogram, _ObservableCounter, _ObservableGauge, _ObservableUpDownCounter, _UpDownCounter
from opentelemetry.sdk.metrics._internal.measurement_consumer import MeasurementConsumer, SynchronousMeasurementConsumer
from opentelemetry.sdk.metrics._internal.sdk_configuration import SdkConfiguration
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.util.instrumentation import InstrumentationScope
from opentelemetry.util._once import Once
from opentelemetry.util.types import Attributes

_logger = ...
class Meter(APIMeter):
    """See `opentelemetry.metrics.Meter`."""
    def __init__(self, instrumentation_scope: InstrumentationScope, measurement_consumer: MeasurementConsumer) -> None:
        ...
    
    def create_counter(self, name, unit=..., description=...) -> APICounter:
        ...
    
    def create_up_down_counter(self, name, unit=..., description=...) -> APIUpDownCounter:
        ...
    
    def create_observable_counter(self, name, callbacks=..., unit=..., description=...) -> APIObservableCounter:
        ...
    
    def create_histogram(self, name: str, unit: str = ..., description: str = ..., *, explicit_bucket_boundaries_advisory: Optional[Sequence[float]] = ...) -> APIHistogram:
        ...
    
    def create_gauge(self, name, unit=..., description=...) -> APIGauge:
        ...
    
    def create_observable_gauge(self, name, callbacks=..., unit=..., description=...) -> APIObservableGauge:
        ...
    
    def create_observable_up_down_counter(self, name, callbacks=..., unit=..., description=...) -> APIObservableUpDownCounter:
        ...
    


class MeterProvider(APIMeterProvider):
    r"""See `opentelemetry.metrics.MeterProvider`.

    Args:
        metric_readers: Register metric readers to collect metrics from the SDK
            on demand. Each :class:`opentelemetry.sdk.metrics.export.MetricReader` is
            completely independent and will collect separate streams of
            metrics. TODO: reference ``PeriodicExportingMetricReader`` usage with push
            exporters here.
        resource: The resource representing what the metrics emitted from the SDK pertain to.
        shutdown_on_exit: If true, registers an `atexit` handler to call
            `MeterProvider.shutdown`
        views: The views to configure the metric output the SDK

    By default, instruments which do not match any :class:`opentelemetry.sdk.metrics.view.View` (or if no :class:`opentelemetry.sdk.metrics.view.View`\ s
    are provided) will report metrics with the default aggregation for the
    instrument's kind. To disable instruments by default, configure a match-all
    :class:`opentelemetry.sdk.metrics.view.View` with `DropAggregation` and then create :class:`opentelemetry.sdk.metrics.view.View`\ s to re-enable
    individual instruments:

    .. code-block:: python
        :caption: Disable default views

        MeterProvider(
            views=[
                View(instrument_name="*", aggregation=DropAggregation()),
                View(instrument_name="mycounter"),
            ],
            # ...
        )
    """
    _all_metric_readers_lock = ...
    _all_metric_readers = ...
    def __init__(self, metric_readers: Sequence[opentelemetry.sdk.metrics.export.MetricReader] = ..., resource: Optional[Resource] = ..., exemplar_filter: Optional[ExemplarFilter] = ..., shutdown_on_exit: bool = ..., views: Sequence[opentelemetry.sdk.metrics.view.View] = ...) -> None:
        ...
    
    def force_flush(self, timeout_millis: float = ...) -> bool:
        ...
    
    def shutdown(self, timeout_millis: float = ...): # -> None:
        ...
    
    def get_meter(self, name: str, version: Optional[str] = ..., schema_url: Optional[str] = ..., attributes: Optional[Attributes] = ...) -> Meter:
        ...
    


