"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional, Sequence
from opentelemetry.metrics import Instrument
from opentelemetry.sdk.metrics._internal.aggregation import Aggregation
from opentelemetry.sdk.metrics._internal.export import AggregationTemporality
from opentelemetry.sdk.metrics._internal.measurement import Measurement
from opentelemetry.sdk.metrics._internal.point import DataPointT
from opentelemetry.sdk.metrics._internal.view import View

_logger = ...
class _ViewInstrumentMatch:
    def __init__(self, view: View, instrument: Instrument, instrument_class_aggregation: Dict[type, Aggregation]) -> None:
        ...
    
    def conflicts(self, other: _ViewInstrumentMatch) -> bool:
        ...
    
    def consume_measurement(self, measurement: Measurement, should_sample_exemplar: bool = ...) -> None:
        ...
    
    def collect(self, collection_aggregation_temporality: AggregationTemporality, collection_start_nanos: int) -> Optional[Sequence[DataPointT]]:
        ...
    


