"""
This type stub file was generated by pyright.
"""

import opentelemetry.sdk.metrics
from typing import Iterable, Sequence, Union
from opentelemetry.context import Context
from opentelemetry.metrics import CallbackT, Counter as APICounter, Histogram as APIHistogram, ObservableCounter as APIObservableCounter, ObservableGauge as APIObservableGauge, ObservableUpDownCounter as APIObservableUpDownCounter, UpDownCounter as APIUpDownCounter, _Gauge as APIGauge
from opentelemetry.metrics._internal.instrument import CallbackOptions
from opentelemetry.sdk.metrics._internal.measurement import Measurement
from opentelemetry.sdk.util.instrumentation import InstrumentationScope

_logger = ...
_ERROR_MESSAGE = ...
class _Synchronous:
    def __init__(self, name: str, instrumentation_scope: InstrumentationScope, measurement_consumer: opentelemetry.sdk.metrics.MeasurementConsumer, unit: str = ..., description: str = ...) -> None:
        ...
    


class _Asynchronous:
    def __init__(self, name: str, instrumentation_scope: InstrumentationScope, measurement_consumer: opentelemetry.sdk.metrics.MeasurementConsumer, callbacks: Iterable[CallbackT] | None = ..., unit: str = ..., description: str = ...) -> None:
        ...
    
    def callback(self, callback_options: CallbackOptions) -> Iterable[Measurement]:
        ...
    


class Counter(_Synchronous, APICounter):
    def __new__(cls, *args, **kwargs): # -> Self:
        ...
    
    def add(self, amount: Union[int, float], attributes: dict[str, str] | None = ..., context: Context | None = ...): # -> None:
        ...
    


class UpDownCounter(_Synchronous, APIUpDownCounter):
    def __new__(cls, *args, **kwargs): # -> Self:
        ...
    
    def add(self, amount: Union[int, float], attributes: dict[str, str] | None = ..., context: Context | None = ...): # -> None:
        ...
    


class ObservableCounter(_Asynchronous, APIObservableCounter):
    def __new__(cls, *args, **kwargs): # -> Self:
        ...
    


class ObservableUpDownCounter(_Asynchronous, APIObservableUpDownCounter):
    def __new__(cls, *args, **kwargs): # -> Self:
        ...
    


class Histogram(_Synchronous, APIHistogram):
    def __init__(self, name: str, instrumentation_scope: InstrumentationScope, measurement_consumer: opentelemetry.sdk.metrics.MeasurementConsumer, unit: str = ..., description: str = ..., explicit_bucket_boundaries_advisory: Sequence[float] | None = ...) -> None:
        ...
    
    def __new__(cls, *args, **kwargs): # -> Self:
        ...
    
    def record(self, amount: Union[int, float], attributes: dict[str, str] | None = ..., context: Context | None = ...): # -> None:
        ...
    


class Gauge(_Synchronous, APIGauge):
    def __new__(cls, *args, **kwargs): # -> Self:
        ...
    
    def set(self, amount: Union[int, float], attributes: dict[str, str] | None = ..., context: Context | None = ...): # -> None:
        ...
    


class ObservableGauge(_Asynchronous, APIObservableGauge):
    def __new__(cls, *args, **kwargs): # -> Self:
        ...
    


class _Counter(Counter):
    ...


class _UpDownCounter(UpDownCounter):
    ...


class _ObservableCounter(ObservableCounter):
    ...


class _ObservableUpDownCounter(ObservableUpDownCounter):
    ...


class _Histogram(Histogram):
    ...


class _Gauge(Gauge):
    ...


class _ObservableGauge(ObservableGauge):
    ...


