"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Union
from opentelemetry.context import Context
from opentelemetry.metrics import Instrument
from opentelemetry.util.types import Attributes

@dataclass(frozen=True)
class Measurement:
    """
    Represents a data point reported via the metrics API to the SDK.

    Attributes
        value: Measured value
        time_unix_nano: The time the API call was made to record the Measurement
        instrument: The instrument that produced this `Measurement`.
        context: The active Context of the Measurement at API call time.
        attributes: Measurement attributes
    """
    value: Union[int, float]
    time_unix_nano: int
    instrument: Instrument
    context: Context
    attributes: Attributes = ...


