"""
This type stub file was generated by pyright.
"""

import opentelemetry.sdk.metrics
import opentelemetry.sdk.metrics._internal.instrument
from abc import ABC, abstractmethod
from typing import Iterable, Optional
from opentelemetry.sdk.metrics._internal.measurement import Measurement
from opentelemetry.sdk.metrics._internal.point import Metric

class MeasurementConsumer(ABC):
    @abstractmethod
    def consume_measurement(self, measurement: Measurement) -> None:
        ...
    
    @abstractmethod
    def register_asynchronous_instrument(self, instrument: opentelemetry.sdk.metrics._internal.instrument_Asynchronous): # -> None:
        ...
    
    @abstractmethod
    def collect(self, metric_reader: opentelemetry.sdk.metrics.MetricReader, timeout_millis: float = ...) -> Optional[Iterable[Metric]]:
        ...
    


class SynchronousMeasurementConsumer(MeasurementConsumer):
    def __init__(self, sdk_config: opentelemetry.sdk.metrics._internal.SdkConfiguration) -> None:
        ...
    
    def consume_measurement(self, measurement: Measurement) -> None:
        ...
    
    def register_asynchronous_instrument(self, instrument: opentelemetry.sdk.metrics._internal.instrument._Asynchronous) -> None:
        ...
    
    def collect(self, metric_reader: opentelemetry.sdk.metrics.MetricReader, timeout_millis: float = ...) -> Optional[Iterable[Metric]]:
        ...
    


