"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from opentelemetry.sdk.metrics._internal.aggregation import Aggregation
from opentelemetry.sdk.metrics._internal.export import AggregationTemporality
from opentelemetry.sdk.metrics._internal.measurement import Measurement
from opentelemetry.sdk.metrics._internal.point import MetricsData
from opentelemetry.sdk.metrics._internal.sdk_configuration import SdkConfiguration

_logger = ...
_DEFAULT_VIEW = ...
class MetricReaderStorage:
    """The SDK's storage for a given reader"""
    def __init__(self, sdk_config: SdkConfiguration, instrument_class_temporality: Dict[type, AggregationTemporality], instrument_class_aggregation: Dict[type, Aggregation]) -> None:
        ...
    
    def consume_measurement(self, measurement: Measurement, should_sample_exemplar: bool = ...) -> None:
        ...
    
    def collect(self) -> Optional[MetricsData]:
        ...
    


