"""
This type stub file was generated by pyright.
"""

import opentelemetry.sdk.metrics
import opentelemetry.sdk.resources
from dataclasses import dataclass
from typing import Sequence

@dataclass
class SdkConfiguration:
    exemplar_filter: opentelemetry.sdk.metrics.ExemplarFilter
    resource: opentelemetry.sdk.resources.Resource
    metric_readers: Sequence[opentelemetry.sdk.metrics.MetricReader]
    views: Sequence[opentelemetry.sdk.metrics.View]
    ...


