"""
This type stub file was generated by pyright.
"""

"""Client and server classes corresponding to protobuf-defined services."""
GRPC_GENERATED_VERSION = ...
GRPC_VERSION = ...
EXPECTED_ERROR_RELEASE = ...
SCHEDULED_RELEASE_DATE = ...
_version_not_supported = ...
_version_not_supported = ...
if _version_not_supported:
    ...
class MetricsServiceStub:
    """Service that can be used to push metrics between one Application
    instrumented with OpenTelemetry and a collector, or between a collector and a
    central collector.
    """
    def __init__(self, channel) -> None:
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        ...
    


class MetricsServiceServicer:
    """Service that can be used to push metrics between one Application
    instrumented with OpenTelemetry and a collector, or between a collector and a
    central collector.
    """
    def Export(self, request, context):
        """Missing associated documentation comment in .proto file."""
        ...
    


def add_MetricsServiceServicer_to_server(servicer, server): # -> None:
    ...

class MetricsService:
    """Service that can be used to push metrics between one Application
    instrumented with OpenTelemetry and a collector, or between a collector and a
    central collector.
    """
    @staticmethod
    def Export(request, target, options=..., channel_credentials=..., call_credentials=..., insecure=..., compression=..., wait_for_ready=..., timeout=..., metadata=...):
        ...
    


