"""
This type stub file was generated by pyright.
"""

import collections
import enum
import inspect
import logging
import os
import threading
import time
import weakref
from abc import abstractmethod
from typing import Generic, Optional, Protocol, TypeVar
from opentelemetry.context import _SUPPRESS_INSTRUMENTATION_KEY, attach, detach, set_value
from opentelemetry.util._once import Once

class DuplicateFilter(logging.Filter):
    """Filter that can be applied to internal `logger`'s.

    Currently applied to `logger`s on the export logs path that could otherwise cause endless logging of errors or a
    recursion depth exceeded issue in cases where logging itself results in an exception."""
    def filter(self, record): # -> bool:
        ...
    


class BatchExportStrategy(enum.Enum):
    EXPORT_ALL = ...
    EXPORT_WHILE_BATCH_EXCEEDS_THRESHOLD = ...
    EXPORT_AT_LEAST_ONE_BATCH = ...


Telemetry = TypeVar("Telemetry")
class Exporter(Protocol[Telemetry]):
    @abstractmethod
    def export(self, batch: list[Telemetry], /):
        ...
    
    @abstractmethod
    def shutdown(self):
        ...
    


class BatchProcessor(Generic[Telemetry]):
    """This class can be used with exporter's that implement the above
    Exporter interface to buffer and send telemetry in batch through
     the exporter."""
    def __init__(self, exporter: Exporter[Telemetry], schedule_delay_millis: float, max_export_batch_size: int, export_timeout_millis: float, max_queue_size: int, exporting: str) -> None:
        ...
    
    def worker(self): # -> None:
        ...
    
    def emit(self, data: Telemetry) -> None:
        ...
    
    def shutdown(self, timeout_millis: int = ...): # -> None:
        ...
    
    def force_flush(self, timeout_millis: Optional[int] = ...) -> bool:
        ...
    


